[package]
name = "lattice_qft"
version = "0.1.0"
edition = "2021"
default-run = "cluster_sim"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.0"
rand = "0.8.5"

[profile.dev]
opt-level = 3

[[bin]]
name = "metropolis-test"
path = "src/bin/metropolis_test"

[[bin]]
name = "cluster-sim"
path = "src/bin/cluster_sim"