use crate::{
    action::Action,
    export::{ObsChain, SimResult},
    field::{Field, Field3d},
    lattice::{Lattice, Lattice3d},
};
use rand::prelude::*;
use std::ops::{Add, Deref, DerefMut, Div, Mul, Sub};

pub trait Metropolis: Action {
    fn metropolis_single(&mut self, index: usize, temp: f64, rng: &mut ThreadRng);

    fn metropolis_random(&mut self, temp: f64) {
        let mut rng = ThreadRng::default();
        let index: usize = rng.gen_range(0..Self::SIZE);
        self.metropolis_single(index, temp, &mut rng);
    }

    fn metropolis_sweep(&mut self, temp: f64) {
        let mut rng = ThreadRng::default();
        for index in 0..Self::SIZE {
            self.metropolis_single(index, temp, &mut rng);
        }
    }
}

impl<'a, T, const D: usize, const SIZE: usize> Metropolis for Field<'a, T, D, SIZE>
where
    f64: From<T>,
    T: Add<Output = T>
        + Sub<Output = T>
        + Mul<Output = T>
        + Div<Output = T>
        + Default
        + From<i8>
        + Into<i64>
        + Into<f64>
        + PartialOrd
        + Copy,
    [(); D * 2_usize]:,
{
    fn metropolis_single(&mut self, index: usize, temp: f64, rng: &mut ThreadRng) {
        // Initialize the change to be measured
        let mut new_field = self.clone();
        let coin: bool = rng.gen();
        new_field.values[index] = match coin {
            true => new_field.values[index] + Self::FieldType::from(1_i8),
            false => new_field.values[index] - Self::FieldType::from(1_i8),
        };

        // Calculate the action of both possibilities
        let action = self.action_observable();
        let new_action = new_field.action_observable();

        // Accept the new action if its lower than the previous.
        // Else accept it with a proportional probability.
        let draw: f64 = rng.gen_range(0.0..=1.0);
        let prob: f64 = (((action - new_action) as f64) * temp).exp();
        if draw <= prob {
            *self = new_field;
        }
    }
}

impl<'a, T, const MAX_X: usize, const MAX_Y: usize, const MAX_T: usize> Metropolis
    for Field3d<'a, T, MAX_X, MAX_Y, MAX_T>
where
    f64: From<T>,
    T: Add<Output = T>
        + Sub<Output = T>
        + Mul<Output = T>
        + Div<Output = T>
        + Default
        + From<i8>
        + Into<i64>
        + Into<f64>
        + PartialOrd
        + Copy,
    [(); MAX_X * MAX_Y * MAX_T]:,
{
    fn metropolis_single(&mut self, index: usize, temp: f64, rng: &mut ThreadRng) {
        self.deref_mut().metropolis_single(index, temp, rng)
    }
}

// ----------------------------------------------------------------------------

pub fn metropolis_simulation<const D: usize, const SIZE: usize>(
    lattice: &Lattice<D, SIZE>,
    temp: f64,
    burnin: usize,
    iterations: usize,
) -> (SimResult, ObsChain)
where
    [(); D * 2_usize]:,
{
    // Initialize a field to compare against
    let field: Field<i8, D, SIZE> = Field::random(&lattice);
    let mut field: Field<i32, D, SIZE> = Field::from_field(field);

    // Sweeps to achieve equilibrium
    for _ in 0..burnin {
        field.metropolis_sweep(temp);
    }

    // After having reached equilibrium, for each consecutive field configuration
    // that is generated by the markov chain, we calculate the observable and average it.
    let mut sim_obs_ary: Vec<f64> = Vec::with_capacity(iterations); // Simulation observable arrray
    for _sweeps in 0..iterations {
        field.metropolis_sweep(temp);
        sim_obs_ary.push(field.lattice_action(temp));
    }

    // Mean value of the lattice actions generated by the sim
    let observable: f64 = sim_obs_ary.iter().sum::<f64>() / sim_obs_ary.len() as f64;

    let data: ObsChain = ObsChain::new(sim_obs_ary);

    let results: SimResult = SimResult::new(temp, burnin, iterations, observable, None);

    println!("Metropolis {:?}", results);

    (results, data)
}

pub fn metropolis_simulation3d<const MAX_X: usize, const MAX_Y: usize, const MAX_T: usize>(
    lattice: &Lattice3d<MAX_X, MAX_Y, MAX_T>,
    temp: f64,
    burnin: usize,
    iterations: usize,
) -> (SimResult, ObsChain)
where
    [(); MAX_X * MAX_Y * MAX_T]:,
{
    let lattice = lattice.deref();
    metropolis_simulation(lattice, temp, burnin, iterations)
}
